---
title: "Github and version control"
output: github_document
---

#Github and version control
###August Hao

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Previously in the topic 'Project scaffolding' I talked about what version control is and what you can do to make your workflow more manageable. In this topic I'm going to provide some general resources on how to use Github for version control. Because ~~I am lazy~~ the topic requires quite a bit of screenshot demonstration and there are plenty of resources available on the internet, instead of demonstrating how to do it myself, I will provide links to how other people demonstrated it (and probably did a much better job than I ever would).  

##Why or why not should you use GitHub?

I'm not a big proponent for using GitHub at all. I feel GitHub or any sort of formal Version control measure is a situational thing. There are a number of pros and cons of using version control, but in general using Version control is more or less a habit thing: some people do it as a habit and benefit from it a lot, some people don't because it takes a bit of time to get into --- both are fine.  

####pros:  

Version control helps a lot when you deal with projects that take a very long time to finish (for example, a master research project), simply because we as humans tend to forget things. With something like GitHub, you will be able to track all the changes and progresses you made in your project, and therefore be able to remember what you did (and potentially what you need to amend).  

Version control is also great when you share a project with other people, because it makes any change anyone makes  transparent and reversible. But again, sharing your project with people is not necessary.  

####cons:  

Version control can be redundant for small and quick projects. there is a balance between using version control to save yourself some time and spending unnecessary time because of using version control. Again, this is up to your personal experience and how efficient you are with it.  

The real hard limit to version control is the size limit to your repositories. For example, GitHub only allows for repositories roughly less than 1gb big. Naturally this is not a problem if your repository consists of only scripts and documents, but when there is data involved (especially GIS data), this size limit might become a problem.  

***

##GitHub links

As I said, many of the pages on the internet teach GitHub better than I could, so here are some links that may be useful to you for learning GitHub.

###[GitHub homepage](https://github.com/)

In case you were too lazy to Google, this is the link to GitHub homepage. Remember that after you sign up with GitHub, you can get free access to using private repositories by affiliating your account with your institute ([here](https://education.github.com/)).  

<http://r-bio.github.io/intro-git-rstudio/> This is a good starting point to understand how GitHub works with RStudio

<http://www.molecularecologist.com/2013/11/using-github-with-r-and-rstudio/> Similar to before but with moer practical instructions

<https://www.r-bloggers.com/rstudio-and-github/> Another alternative

<https://guides.github.com/activities/hello-world/> GitHub's official introduction material

